 INSERT INTO Album (Title, ArtistId) VALUES ('Vector Vixens Volume II',1);
 INSERT INTO Album (Title, ArtistId) VALUES ('World Class Chill',2);
 INSERT INTO Album (Title, ArtistId) VALUES ('Critical Heart',2);
 INSERT INTO Album (Title, ArtistId) VALUES ('Tech Bass Life',1);
 INSERT INTO Album (Title, ArtistId) VALUES ('Action After Life',3);
 INSERT INTO Album (Title, ArtistId) VALUES ('Collaborative Rock',4);
 INSERT INTO Album (Title, ArtistId) VALUES ('Revolutionary Hype',5);
 INSERT INTO Album (Title, ArtistId) VALUES ('Compelling Nurses',6);
 INSERT INTO Album (Title, ArtistId) VALUES ('Turn Hop Time',7);
 INSERT INTO Album (Title, ArtistId) VALUES ('Reinvent Dog Days',8);
 INSERT INTO Album (Title, ArtistId) VALUES ('Best Of Breed',8);
 INSERT INTO Album (Title, ArtistId) VALUES ('Target Slam',9);
 INSERT INTO Album (Title, ArtistId) VALUES ('Efficient Beats',10);
 INSERT INTO Album (Title, ArtistId) VALUES ('Next Generation Guys',11);
 INSERT INTO Album (Title, ArtistId) VALUES ('Granular Grape',11);
 INSERT INTO Album (Title, ArtistId) VALUES ('Cross Chick Cool',12);
 INSERT INTO Album (Title, ArtistId) VALUES ('Transform Edge Vortals',12);
 INSERT INTO Album (Title, ArtistId) VALUES ('Clicks And Mortar',13);
 INSERT INTO Album (Title, ArtistId) VALUES ('Umbrella Architecture Wrap',14);
 INSERT INTO Album (Title, ArtistId) VALUES ('Envisioneer Interactive',15);
 INSERT INTO Album (Title, ArtistId) VALUES ('Enhanced Friction',16);
 INSERT INTO Album (Title, ArtistId) VALUES ('Dot Com Mindshare',16);
 INSERT INTO Album (Title, ArtistId) VALUES ('Harness Partnerships',17);
 INSERT INTO Album (Title, ArtistId) VALUES ('Maximize Best Time',18);
 INSERT INTO Album (Title, ArtistId) VALUES ('Matrix Play Puppy',18);
 INSERT INTO Album (Title, ArtistId) VALUES ('Money Real Five',19);
 INSERT INTO Album (Title, ArtistId) VALUES ('Dynamic Hip Fresh',19);
 INSERT INTO Album (Title, ArtistId) VALUES ('Back In The Day',20);
 INSERT INTO Album (Title, ArtistId) VALUES ('Incubate',21);
 INSERT INTO Album (Title, ArtistId) VALUES ('Distributed Depliomats',22);
 INSERT INTO Album (Title, ArtistId) VALUES ('Extra Sands Linked',23);
 INSERT INTO Album (Title, ArtistId) VALUES ('End To End Method Rock',21);
 INSERT INTO Album (Title, ArtistId) VALUES ('Virtual Vibes',24);
 INSERT INTO Album (Title, ArtistId) VALUES ('Timely Tickle Yap',6);
 INSERT INTO Album (Title, ArtistId) VALUES ('Easy Beats No Longer',50);
 INSERT INTO Album (Title, ArtistId) VALUES ('Target Breed Applications',51);
 INSERT INTO Album (Title, ArtistId) VALUES ('Leverage',52);
 INSERT INTO Album (Title, ArtistId) VALUES ('Wisdom Swap',53);
 INSERT INTO Album (Title, ArtistId) VALUES ('Positive People',54);
 INSERT INTO Album (Title, ArtistId) VALUES ('Ubiquitous Mindshare',55);
 INSERT INTO Album (Title, ArtistId) VALUES ('User Centric Tunes',56);
 INSERT INTO Album (Title, ArtistId) VALUES ('Convergence Baby',57);
 INSERT INTO Album (Title, ArtistId) VALUES ('Methodology Melody',58);
 INSERT INTO Album (Title, ArtistId) VALUES ('Fire Visionary',22);
 INSERT INTO Album (Title, ArtistId) VALUES ('Sticky Feet',21);
 INSERT INTO Album (Title, ArtistId) VALUES ('Rose Water',59);
 INSERT INTO Album (Title, ArtistId) VALUES ('Open Portal Grad',37);
 INSERT INTO Album (Title, ArtistId) VALUES ('Cultivate Love',68);
 INSERT INTO Album (Title, ArtistId) VALUES ('Channel Hype',68);
 INSERT INTO Album (Title, ArtistId) VALUES ('Embracing District Drones',58);
 INSERT INTO Album (Title, ArtistId) VALUES ('Vortex Funny Boy',69);
 INSERT INTO Album (Title, ArtistId) VALUES ('Hip Star Sunny',70);
 INSERT INTO Album (Title, ArtistId) VALUES ('Bleeding Edge Trap',21);
 INSERT INTO Album (Title, ArtistId) VALUES ('Robot Infrastructures',76);
 INSERT INTO Album (Title, ArtistId) VALUES ('Harness Security Mixer',76);
 INSERT INTO Album (Title, ArtistId) VALUES ('Grown And Sassy',77);
 INSERT INTO Album (Title, ArtistId) VALUES ('Twenty Four Hipster',77);
 INSERT INTO Album (Title, ArtistId) VALUES ('Relationship Hater',58);
 INSERT INTO Album (Title, ArtistId) VALUES ('Drive Key Portals',58);
 INSERT INTO Album (Title, ArtistId) VALUES ('Yo Hendrix Cool',58);
 INSERT INTO Album (Title, ArtistId) VALUES ('Nowhere To Go',58);
 INSERT INTO Album (Title, ArtistId) VALUES ('Party Star Rock',58);
 INSERT INTO Album (Title, ArtistId) VALUES ('Click Brainstorm Poppy',58);
 INSERT INTO Album (Title, ArtistId) VALUES ('Cut To The Chase',58);
 INSERT INTO Album (Title, ArtistId) VALUES ('Wear Everthing Out',58);
 INSERT INTO Album (Title, ArtistId) VALUES ('Rent Be Due',58);
 INSERT INTO Album (Title, ArtistId) VALUES ('Hey Hey Hey',78);
 INSERT INTO Album (Title, ArtistId) VALUES ('Mapped Beat Global',79);
 INSERT INTO Album (Title, ArtistId) VALUES ('Story Time All The Time',80);
 INSERT INTO Album (Title, ArtistId) VALUES ('Media Minded Meddlers',80);
 INSERT INTO Album (Title, ArtistId) VALUES ('Evolving Echo',41);
 INSERT INTO Album (Title, ArtistId) VALUES ('Snap Clap Whistle',81);
 INSERT INTO Album (Title, ArtistId) VALUES ('Evicted',81);
 INSERT INTO Album (Title, ArtistId) VALUES ('Big Deal',82);
 INSERT INTO Album (Title, ArtistId) VALUES ('Friends',82);
 INSERT INTO Album (Title, ArtistId) VALUES ('Liars Hanging On The Corner',82);
 INSERT INTO Album (Title, ArtistId) VALUES ('Breezey Ice Breaker',82);
 INSERT INTO Album (Title, ArtistId) VALUES ('Get Hyped',83);
 INSERT INTO Album (Title, ArtistId) VALUES ('Iterate',84);
 INSERT INTO Album (Title, ArtistId) VALUES ('Blue Album',84);
 INSERT INTO Album (Title, ArtistId) VALUES ('Riot Hits II',84);
 INSERT INTO Album (Title, ArtistId) VALUES ('Action Just In Time',84);
 INSERT INTO Album (Title, ArtistId) VALUES ('Next Generation Ex',85);
 INSERT INTO Album (Title, ArtistId) VALUES ('Synergize Niches In HiDef',86);
 INSERT INTO Album (Title, ArtistId) VALUES ('Apple Core Tunes',27);
 INSERT INTO Album (Title, ArtistId) VALUES ('Door Days',27);
 INSERT INTO Album (Title, ArtistId) VALUES ('Volume Booster',27);
 INSERT INTO Album (Title, ArtistId) VALUES ('Hoodoo Beyond Step',87);
 INSERT INTO Album (Title, ArtistId) VALUES ('Infrastructures Wop',54);
 INSERT INTO Album (Title, ArtistId) VALUES ('Viral Action Lost',88);
 INSERT INTO Album (Title, ArtistId) VALUES ('Platform Boogie',88);
 INSERT INTO Album (Title, ArtistId) VALUES ('Compelling Sisters',88);
 INSERT INTO Album (Title, ArtistId) VALUES ('embrace clicks-and-mortar platforms',89);
 INSERT INTO Album (Title, ArtistId) VALUES ('Front Business',90);
 INSERT INTO Album (Title, ArtistId) VALUES ('Visualize Happy',90);
 INSERT INTO Album (Title, ArtistId) VALUES ('Open Closed Shut',90);
 INSERT INTO Album (Title, ArtistId) VALUES ('Drill Back War',90);
 INSERT INTO Album (Title, ArtistId) VALUES ('House Cost Everything',90);
 INSERT INTO Album (Title, ArtistId) VALUES ('Streaming Sounds',90);
 INSERT INTO Album (Title, ArtistId) VALUES ('Landlord',90);
 INSERT INTO Album (Title, ArtistId) VALUES ('Band Life',90);
 INSERT INTO Album (Title, ArtistId) VALUES ('Yelling Shower Band',90);
 INSERT INTO Album (Title, ArtistId) VALUES ('Drowning',90);
 INSERT INTO Album (Title, ArtistId) VALUES ('Whole Heart Volume III',90);
 INSERT INTO Album (Title, ArtistId) VALUES ('Impactful Beats',90);
 INSERT INTO Album (Title, ArtistId) VALUES ('Convergence Life Love',90);
 INSERT INTO Album (Title, ArtistId) VALUES ('Embrace Sizzle Bop',90);
 INSERT INTO Album (Title, ArtistId) VALUES ('Chaos Boot Beats',90);
 INSERT INTO Album (Title, ArtistId) VALUES ('Magnetic Music',90);
 INSERT INTO Album (Title, ArtistId) VALUES ('Morph Contraband',90);
 INSERT INTO Album (Title, ArtistId) VALUES ('Settle The Score',90);
 INSERT INTO Album (Title, ArtistId) VALUES ('Killer Ramp Rock',90);
 INSERT INTO Album (Title, ArtistId) VALUES ('Niches Next Time',90);
 INSERT INTO Album (Title, ArtistId) VALUES ('Webster Wax',90);
 INSERT INTO Album (Title, ArtistId) VALUES ('Fast Talker',91);
 INSERT INTO Album (Title, ArtistId) VALUES ('Yoga Yuppie',92);
 INSERT INTO Album (Title, ArtistId) VALUES ('Zootopick',92);
 INSERT INTO Album (Title, ArtistId) VALUES ('Public Costume Dancer',92);
 INSERT INTO Album (Title, ArtistId) VALUES ('Unleashed Beats Volume I',93);
 INSERT INTO Album (Title, ArtistId) VALUES ('Seize Top Beat Love',94);
 INSERT INTO Album (Title, ArtistId) VALUES ('Metric Music Muse',95);
 INSERT INTO Album (Title, ArtistId) VALUES ('System Storage Van',46);
 INSERT INTO Album (Title, ArtistId) VALUES ('Right Left Center',96);
 INSERT INTO Album (Title, ArtistId) VALUES ('Sexy Sassy Coward',97);
 INSERT INTO Album (Title, ArtistId) VALUES ('Hum Hush Puppy',98);
 INSERT INTO Album (Title, ArtistId) VALUES ('All The Words',52);
 INSERT INTO Album (Title, ArtistId) VALUES ('Carmin The Cattastick',22);
 INSERT INTO Album (Title, ArtistId) VALUES ('New Things Old Things',22);
 INSERT INTO Album (Title, ArtistId) VALUES ('Waltz Music Galaxy',22);
 INSERT INTO Album (Title, ArtistId) VALUES ('Eyeballs Hunt Legacy',22);
 INSERT INTO Album (Title, ArtistId) VALUES ('Back To The Yard',22);
 INSERT INTO Album (Title, ArtistId) VALUES ('Seven Lovely Gifts',22);
 INSERT INTO Album (Title, ArtistId) VALUES ('Folk Gonna Funk',22);
 INSERT INTO Album (Title, ArtistId) VALUES ('Getaway Gritty Brothers',22);
 INSERT INTO Album (Title, ArtistId) VALUES ('Sir Funk Beat Inspired',22);
 INSERT INTO Album (Title, ArtistId) VALUES ('Wage War Concertos',22);
 INSERT INTO Album (Title, ArtistId) VALUES ('Transform Sound',22);
 INSERT INTO Album (Title, ArtistId) VALUES ('Mission Critical',22);
 INSERT INTO Album (Title, ArtistId) VALUES ('Added Beats By Day',99);
 INSERT INTO Album (Title, ArtistId) VALUES ('Burro Pop',99);
 INSERT INTO Album (Title, ArtistId) VALUES ('Salty But Sweet',100);
 INSERT INTO Album (Title, ArtistId) VALUES ('Evening Dance',101);
 INSERT INTO Album (Title, ArtistId) VALUES ('Aqua Rich Rhythm',101);
 INSERT INTO Album (Title, ArtistId) VALUES ('Purple Zoo',102);
 INSERT INTO Album (Title, ArtistId) VALUES ('All The Time',103);
 INSERT INTO Album (Title, ArtistId) VALUES ('We Take Each Step',104);
 INSERT INTO Album (Title, ArtistId) VALUES ('Sugar Honey Pie',105);
 INSERT INTO Album (Title, ArtistId) VALUES ('Life Lived Out Loud',50);
 INSERT INTO Album (Title, ArtistId) VALUES ('Samba Serious',50);
 INSERT INTO Album (Title, ArtistId) VALUES ('Side Of The Sun',50);
 INSERT INTO Album (Title, ArtistId) VALUES ('Holistic Heartbeat',50);
 INSERT INTO Album (Title, ArtistId) VALUES ('Bricks Cars And Trucks',50);
 INSERT INTO Album (Title, ArtistId) VALUES ('Hip Hop Greatest Hits',50);
 INSERT INTO Album (Title, ArtistId) VALUES ('Sleeping After Noon',50);
 INSERT INTO Album (Title, ArtistId) VALUES ('CafŽ Copa Pop',50);
 INSERT INTO Album (Title, ArtistId) VALUES ('Funkphonic Palooza',50);
 INSERT INTO Album (Title, ArtistId) VALUES ('The Fake One',68);
 INSERT INTO Album (Title, ArtistId) VALUES ('Plugged In To The Sound',42);
 INSERT INTO Album (Title, ArtistId) VALUES ('Unleased Boom Beats',42);
 INSERT INTO Album (Title, ArtistId) VALUES ('The Real Classics',106);
 INSERT INTO Album (Title, ArtistId) VALUES ('World Wide Sound Hound',108);
 INSERT INTO Album (Title, ArtistId) VALUES ('Light Layered Love',109);
 INSERT INTO Album (Title, ArtistId) VALUES ('Pasta Mix Volume VI',110);
 INSERT INTO Album (Title, ArtistId) VALUES ('Master Mix Volume II',110);
 INSERT INTO Album (Title, ArtistId) VALUES ('Carnaval Party: Trinidad',111);
 INSERT INTO Album (Title, ArtistId) VALUES ('One Time For The Lovers',112);
 INSERT INTO Album (Title, ArtistId) VALUES ('Where When Why',113);
 INSERT INTO Album (Title, ArtistId) VALUES ('Hoot Drums Strings',113);
 INSERT INTO Album (Title, ArtistId) VALUES ('Evolution Syndicate',113);
 INSERT INTO Album (Title, ArtistId) VALUES ('Mesh Magenta Money',114);
 INSERT INTO Album (Title, ArtistId) VALUES ('Brazil Brilliant Beats',114);
 INSERT INTO Album (Title, ArtistId) VALUES ('Vocals On Fire',114);
 INSERT INTO Album (Title, ArtistId) VALUES ('White Sands Sun Rise',114);
 INSERT INTO Album (Title, ArtistId) VALUES ('Tropical Times With You',114);
 INSERT INTO Album (Title, ArtistId) VALUES ('Dance Dance Get Up',115);
 INSERT INTO Album (Title, ArtistId) VALUES ('Dust Off Those Dance Shoes',116);
 INSERT INTO Album (Title, ArtistId) VALUES ('Moody Music Volume III',117);
 INSERT INTO Album (Title, ArtistId) VALUES ('Iron Feet',118);
 INSERT INTO Album (Title, ArtistId) VALUES ('Number One Guy',118);
 INSERT INTO Album (Title, ArtistId) VALUES ('Coffee Grinder',118);
 INSERT INTO Album (Title, ArtistId) VALUES ('Be With Me Today',118);
 INSERT INTO Album (Title, ArtistId) VALUES ('Touched',118);
 INSERT INTO Album (Title, ArtistId) VALUES ('Joyful Moments With You',120);
 INSERT INTO Album (Title, ArtistId) VALUES ('Ace Jet Always',121);
 INSERT INTO Album (Title, ArtistId) VALUES ('Feeling Good',51);
 INSERT INTO Album (Title, ArtistId) VALUES ('Baby Nino',51);
 INSERT INTO Album (Title, ArtistId) VALUES ('California Sleeping',122);
 INSERT INTO Album (Title, ArtistId) VALUES ('Live Banana Boy',124);
 INSERT INTO Album (Title, ArtistId) VALUES ('Counting Cherries',124);
 INSERT INTO Album (Title, ArtistId) VALUES ('International Ladies',124);
 INSERT INTO Album (Title, ArtistId) VALUES ('The Best of Walter',125);
 INSERT INTO Album (Title, ArtistId) VALUES ('Vault Times Two',126);
 INSERT INTO Album (Title, ArtistId) VALUES ('repurpose virtual platforms',127);
 INSERT INTO Album (Title, ArtistId) VALUES ('transition scalable ROI',127);
 INSERT INTO Album (Title, ArtistId) VALUES ('Custom Cream of Tarter',127);
 INSERT INTO Album (Title, ArtistId) VALUES ('Deluxe Disaster',128);
 INSERT INTO Album (Title, ArtistId) VALUES ('Blindsided Betty',59);
 INSERT INTO Album (Title, ArtistId) VALUES ('Red Rider Rocker',59);
 INSERT INTO Album (Title, ArtistId) VALUES ('Work Play Rest',130);
 INSERT INTO Album (Title, ArtistId) VALUES ('Looking Back',130);
 INSERT INTO Album (Title, ArtistId) VALUES ('Stumbling Stereo',131);
 INSERT INTO Album (Title, ArtistId) VALUES ('All Night Long',131);
 INSERT INTO Album (Title, ArtistId) VALUES ('Fairy Mother Tunes',132);
 INSERT INTO Album (Title, ArtistId) VALUES ('Jealousy',53);
 INSERT INTO Album (Title, ArtistId) VALUES ('Living Out Loud',133);
 INSERT INTO Album (Title, ArtistId) VALUES ('Overcome',134);
 INSERT INTO Album (Title, ArtistId) VALUES ('Strong Confidence',135);
 INSERT INTO Album (Title, ArtistId) VALUES ('Step Up Step Out',136);
 INSERT INTO Album (Title, ArtistId) VALUES ('Freedom',137);
 INSERT INTO Album (Title, ArtistId) VALUES ('Transferred Tire Pool',137);
 INSERT INTO Album (Title, ArtistId) VALUES ('Clowning Around',138);
 INSERT INTO Album (Title, ArtistId) VALUES ('House Treat',139);
 INSERT INTO Album (Title, ArtistId) VALUES ('No World',139);
 INSERT INTO Album (Title, ArtistId) VALUES ('Free Beats Volume I',140);
 INSERT INTO Album (Title, ArtistId) VALUES ('Shut Down And Dance',141);
 INSERT INTO Album (Title, ArtistId) VALUES ('Dangerous Doubt',142);
 INSERT INTO Album (Title, ArtistId) VALUES ('Hangover',142);
 INSERT INTO Album (Title, ArtistId) VALUES ('New York Sacrafice',142);
 INSERT INTO Album (Title, ArtistId) VALUES ('Fairytell',143);
 INSERT INTO Album (Title, ArtistId) VALUES ('Boyfriend',143);
 INSERT INTO Album (Title, ArtistId) VALUES ('This Is Me',144);
 INSERT INTO Album (Title, ArtistId) VALUES ('Jersey Shore',145);
 INSERT INTO Album (Title, ArtistId) VALUES ('Honey',145);
 INSERT INTO Album (Title, ArtistId) VALUES ('Brown Dog',146);
 INSERT INTO Album (Title, ArtistId) VALUES ('Freak',146);
 INSERT INTO Album (Title, ArtistId) VALUES ('Crazy Wild Silly',147);
 INSERT INTO Album (Title, ArtistId) VALUES ('Warm And Fuzzy',147);
 INSERT INTO Album (Title, ArtistId) VALUES ('Loud And Proud',148);
 INSERT INTO Album (Title, ArtistId) VALUES ('Taco Tuesday',149);
 INSERT INTO Album (Title, ArtistId) VALUES ('Speak Out Sound The Alarm',149);
 INSERT INTO Album (Title, ArtistId) VALUES ('Sneaky',149);
 INSERT INTO Album (Title, ArtistId) VALUES ('Live In The Moment',150);
 INSERT INTO Album (Title, ArtistId) VALUES ('Global Light',150);
 INSERT INTO Album (Title, ArtistId) VALUES ('Enterprise Inspired',150);
 INSERT INTO Album (Title, ArtistId) VALUES ('School Kid Pop',150);
 INSERT INTO Album (Title, ArtistId) VALUES ('Vertical Sound Chain',150);
 INSERT INTO Album (Title, ArtistId) VALUES ('Driven Digital',150);
 INSERT INTO Album (Title, ArtistId) VALUES ('No Way Not Happening',150);
 INSERT INTO Album (Title, ArtistId) VALUES ('Virtual World Happy',150);
 INSERT INTO Album (Title, ArtistId) VALUES ('Dolphin Diva',150);
 INSERT INTO Album (Title, ArtistId) VALUES ('Cat Temple',151);
 INSERT INTO Album (Title, ArtistId) VALUES ('Yellow Brick Act',152);
 INSERT INTO Album (Title, ArtistId) VALUES ('Change Color Kiss',152);
 INSERT INTO Album (Title, ArtistId) VALUES ('Iggy',152);
 INSERT INTO Album (Title, ArtistId) VALUES ('Calm Family Tunes',152);
 INSERT INTO Album (Title, ArtistId) VALUES ('Gas Diary of Greg',153);
 INSERT INTO Album (Title, ArtistId) VALUES ('Delivered Heart',72);
 INSERT INTO Album (Title, ArtistId) VALUES ('Jazz Damage',155);
 INSERT INTO Album (Title, ArtistId) VALUES ('Journey Through Hope',156);
 INSERT INTO Album (Title, ArtistId) VALUES ('Night Out On The Town',156);
 INSERT INTO Album (Title, ArtistId) VALUES ('Flirt',156);
 INSERT INTO Album (Title, ArtistId) VALUES ('Fiesta All Night',157);
 INSERT INTO Album (Title, ArtistId) VALUES ('Mix It Up',158);
 INSERT INTO Album (Title, ArtistId) VALUES ('Acoustic Jams',159);
 INSERT INTO Album (Title, ArtistId) VALUES ('Goodnight',150);
 INSERT INTO Album (Title, ArtistId) VALUES ('Quiet Times',114);
 INSERT INTO Album (Title, ArtistId) VALUES ('Waves Destiny',179);
 INSERT INTO Album (Title, ArtistId) VALUES ('South African Vampire',180);
 INSERT INTO Album (Title, ArtistId) VALUES ('Dropout',36);
 INSERT INTO Album (Title, ArtistId) VALUES ('Fun Times With Franky',196);
 INSERT INTO Album (Title, ArtistId) VALUES ('Rattle Pizza Party',149);
 INSERT INTO Album (Title, ArtistId) VALUES ('Lightning',197);
 INSERT INTO Album (Title, ArtistId) VALUES ('Shocked Sounds',198);
 INSERT INTO Album (Title, ArtistId) VALUES ('Improved Grooves',199);
 INSERT INTO Album (Title, ArtistId) VALUES ('Love Songs',200);
 INSERT INTO Album (Title, ArtistId) VALUES ('Lilac Album',201);
 INSERT INTO Album (Title, ArtistId) VALUES ('Absolute Best Hits',202);
 INSERT INTO Album (Title, ArtistId) VALUES ('Never Behave',203);
 INSERT INTO Album (Title, ArtistId) VALUES ('Bayshore Beats',204);
 INSERT INTO Album (Title, ArtistId) VALUES ('Party People',205);
 INSERT INTO Album (Title, ArtistId) VALUES ('Wake Up',8);
 INSERT INTO Album (Title, ArtistId) VALUES ('Power To The Puppy',206);
 INSERT INTO Album (Title, ArtistId) VALUES ('Reality Check',207);
 INSERT INTO Album (Title, ArtistId) VALUES ('Machine Man Woman',208);
 INSERT INTO Album (Title, ArtistId) VALUES ('Maxx Effect',209);
 INSERT INTO Album (Title, ArtistId) VALUES ('Speechless',210);
 INSERT INTO Album (Title, ArtistId) VALUES ('Hungry For Soul',211);
 INSERT INTO Album (Title, ArtistId) VALUES ('Dance of Fear',212);
 INSERT INTO Album (Title, ArtistId) VALUES ('Suitcase City',213);
 INSERT INTO Album (Title, ArtistId) VALUES ('Sorry Sara',214);
 INSERT INTO Album (Title, ArtistId) VALUES ('Top Class Band',215);
 INSERT INTO Album (Title, ArtistId) VALUES ('Fight The Monster',216);
 INSERT INTO Album (Title, ArtistId) VALUES ('Birthright',217);
 INSERT INTO Album (Title, ArtistId) VALUES ('Be Here Be Heard',218);
 INSERT INTO Album (Title, ArtistId) VALUES ('Off Road Off Grid',219);
 INSERT INTO Album (Title, ArtistId) VALUES ('Confidence',220);
 INSERT INTO Album (Title, ArtistId) VALUES ('Season Of Sounds',221);
 INSERT INTO Album (Title, ArtistId) VALUES ('Money Beats',222);
 INSERT INTO Album (Title, ArtistId) VALUES ('Get It Done',223);
 INSERT INTO Album (Title, ArtistId) VALUES ('Lake Canyon Band',224);
 INSERT INTO Album (Title, ArtistId) VALUES ('Promise',225);
 INSERT INTO Album (Title, ArtistId) VALUES ('Monkey Feelings',226);
 INSERT INTO Album (Title, ArtistId) VALUES ('Twelve Days Away',227);
 INSERT INTO Album (Title, ArtistId) VALUES ('Playful In Overdrive',228);
 INSERT INTO Album (Title, ArtistId) VALUES ('Bold Beats And Sounds',229);
 INSERT INTO Album (Title, ArtistId) VALUES ('Conservative Classic',230);
 INSERT INTO Album (Title, ArtistId) VALUES ('Get Together',231);
 INSERT INTO Album (Title, ArtistId) VALUES ('The Best Mellow',232);
 INSERT INTO Album (Title, ArtistId) VALUES ('Sadie Sound Cloud',233);
 INSERT INTO Album (Title, ArtistId) VALUES ('Precious Times',234);
 INSERT INTO Album (Title, ArtistId) VALUES ('Back In The Shore',235);
 INSERT INTO Album (Title, ArtistId) VALUES ('Get It In Your Head',236);
 INSERT INTO Album (Title, ArtistId) VALUES ('Father Time',237);
 INSERT INTO Album (Title, ArtistId) VALUES ('Love Me Always',238);
 INSERT INTO Album (Title, ArtistId) VALUES ('Change',240);
 INSERT INTO Album (Title, ArtistId) VALUES ('Wow Greatest Hits Volume III',241);
 INSERT INTO Album (Title, ArtistId) VALUES ('Polkadot Pumpkin Band',242);
 INSERT INTO Album (Title, ArtistId) VALUES ('Fantastic Three',243);
 INSERT INTO Album (Title, ArtistId) VALUES ('Ideology',244);
 INSERT INTO Album (Title, ArtistId) VALUES ('Unthinkable',245);
 INSERT INTO Album (Title, ArtistId) VALUES ('Med Odd Enigma',226);
 INSERT INTO Album (Title, ArtistId) VALUES ('Duo Tag Team Hits',245);
 INSERT INTO Album (Title, ArtistId) VALUES ('Critic Chill Tonight',246);
 INSERT INTO Album (Title, ArtistId) VALUES ('Thinking Thoughts Happy',247);
 INSERT INTO Album (Title, ArtistId) VALUES ('Brain Hip Beats',208);
 INSERT INTO Album (Title, ArtistId) VALUES ('Solution Soul Sounds',248);
 INSERT INTO Album (Title, ArtistId) VALUES ('Spot Hot Beat Party',249);
 INSERT INTO Album (Title, ArtistId) VALUES ('China Downtown',250);
 INSERT INTO Album (Title, ArtistId) VALUES ('Classified Classical Tunes',251);
 INSERT INTO Album (Title, ArtistId) VALUES ('Zoot Hoot Chill',248);
 INSERT INTO Album (Title, ArtistId) VALUES ('Paradigm Party Night',252);
 INSERT INTO Album (Title, ArtistId) VALUES ('Revolution Fight',252);
 INSERT INTO Album (Title, ArtistId) VALUES ('Be Happy',253);
 INSERT INTO Album (Title, ArtistId) VALUES ('Promise Me',254);
 INSERT INTO Album (Title, ArtistId) VALUES ('Crying Tears All Night',255);
 INSERT INTO Album (Title, ArtistId) VALUES ('Number One Priority',256);
 INSERT INTO Album (Title, ArtistId) VALUES ('Jump Up Jump Around',257);
 INSERT INTO Album (Title, ArtistId) VALUES ('Jokes',258);
 INSERT INTO Album (Title, ArtistId) VALUES ('Whiteboard',259);
 INSERT INTO Album (Title, ArtistId) VALUES ('Extensible Chatter Dummies',260);
 INSERT INTO Album (Title, ArtistId) VALUES ('Leverage Global Love',261);
 INSERT INTO Album (Title, ArtistId) VALUES ('Reinvent Tailers',262);
 INSERT INTO Album (Title, ArtistId) VALUES ('Live Transition',263);
 INSERT INTO Album (Title, ArtistId) VALUES ('Mesh Dynamic Pill',264);
 INSERT INTO Album (Title, ArtistId) VALUES ('Delivered Soul',265);
 INSERT INTO Album (Title, ArtistId) VALUES ('Dreamline Networks',248);
 INSERT INTO Album (Title, ArtistId) VALUES ('Back Loud Thrill',266);
 INSERT INTO Album (Title, ArtistId) VALUES ('Envisionee Infomediaries',267);
 INSERT INTO Album (Title, ArtistId) VALUES ('Mission Critical Readiness',268);
 INSERT INTO Album (Title, ArtistId) VALUES ('Global Vortex',269);
 INSERT INTO Album (Title, ArtistId) VALUES ('Deploy Count',270);
 INSERT INTO Album (Title, ArtistId) VALUES ('Synergies Eyeballs',271);
 INSERT INTO Album (Title, ArtistId) VALUES ('Synergize Frictionless',226);
 INSERT INTO Album (Title, ArtistId) VALUES ('Transparent',272);
 INSERT INTO Album (Title, ArtistId) VALUES ('Benchmark Viral',273);
 INSERT INTO Album (Title, ArtistId) VALUES ('Robust Rockers',274);
 INSERT INTO Album (Title, ArtistId) VALUES ('Engage Star',275);