INSERT INTO Artist (Name) VALUES('Lolly');
INSERT INTO Artist (Name) VALUES('Nollie Murie');
INSERT INTO Artist (Name) VALUES('Stephannie Willoughway');
INSERT INTO Artist (Name) VALUES('Plumtree');
INSERT INTO Artist (Name) VALUES('Alfons Balint');
INSERT INTO Artist (Name) VALUES('Hetty Pordal');
INSERT INTO Artist (Name) VALUES('Giorgia Torr');
INSERT INTO Artist (Name) VALUES('Herta Damant');
INSERT INTO Artist (Name) VALUES('Lil Dulce');
INSERT INTO Artist (Name) VALUES('Kearney Meni');
INSERT INTO Artist (Name) VALUES('Alyosha Cuvley');
INSERT INTO Artist (Name) VALUES('Lona Jerg');
INSERT INTO Artist (Name) VALUES('Jemmy Bonanno');
INSERT INTO Artist (Name) VALUES('Ewart Drable');
INSERT INTO Artist (Name) VALUES('Alyssa Halsey');
INSERT INTO Artist (Name) VALUES('Tallulah Gollop');
INSERT INTO Artist (Name) VALUES('Barstow');
INSERT INTO Artist (Name) VALUES('Archie Sugden');
INSERT INTO Artist (Name) VALUES('Alecia Downton');
INSERT INTO Artist (Name) VALUES('Big Conny');
INSERT INTO Artist (Name) VALUES('Duke Loweth');
INSERT INTO Artist (Name) VALUES('Bryn Crunkhurn');
INSERT INTO Artist (Name) VALUES('Yalden');
INSERT INTO Artist (Name) VALUES('Olivie Borsi');
INSERT INTO Artist (Name) VALUES('Elspeth Genders');
INSERT INTO Artist (Name) VALUES('Ricardo');
INSERT INTO Artist (Name) VALUES('Franciska Wankling');
INSERT INTO Artist (Name) VALUES('Crysta Beuscher');
INSERT INTO Artist (Name) VALUES('Ralf Mahedy');
INSERT INTO Artist (Name) VALUES('Diddi');
INSERT INTO Artist (Name) VALUES('Adrianna Prout');
INSERT INTO Artist (Name) VALUES('Albertine Willsmore');
INSERT INTO Artist (Name) VALUES('Fanny');
INSERT INTO Artist (Name) VALUES('Hannis Garry');
INSERT INTO Artist (Name) VALUES('Nobe Tournay');
INSERT INTO Artist (Name) VALUES('Lorinda Farnes');
INSERT INTO Artist (Name) VALUES('Jami Schollick');
INSERT INTO Artist (Name) VALUES('Gabbie Benmore');
INSERT INTO Artist (Name) VALUES('Phaedra');
INSERT INTO Artist (Name) VALUES('Jase Copyn');
INSERT INTO Artist (Name) VALUES('Marline Sancias');
INSERT INTO Artist (Name) VALUES('Crissie Bissell');
INSERT INTO Artist (Name) VALUES('Valentine Hartridge');
INSERT INTO Artist (Name) VALUES('Giffie Dallaghan');
INSERT INTO Artist (Name) VALUES('Casper Gellion');
INSERT INTO Artist (Name) VALUES('Meaddow');
INSERT INTO Artist (Name) VALUES('Lyn Farnill');
INSERT INTO Artist (Name) VALUES('Etan Gilligan');
INSERT INTO Artist (Name) VALUES('Jenda Zorzenoni');
INSERT INTO Artist (Name) VALUES('Dasi Tonge');
INSERT INTO Artist (Name) VALUES('Ivette Spridgeon');
INSERT INTO Artist (Name) VALUES('Fraze Rettie');
INSERT INTO Artist (Name) VALUES('Rhodia Kitchingman');
INSERT INTO Artist (Name) VALUES('Lisabeth Docharty');
INSERT INTO Artist (Name) VALUES('Ade Medhurst');
INSERT INTO Artist (Name) VALUES('Sis Carlene');
INSERT INTO Artist (Name) VALUES('Irena Crudginton');
INSERT INTO Artist (Name) VALUES('Amberly Pinck');
INSERT INTO Artist (Name) VALUES('Allie Looks');
INSERT INTO Artist (Name) VALUES('Elisha Jacop');
INSERT INTO Artist (Name) VALUES('Gil G');
INSERT INTO Artist (Name) VALUES('Mandie Tinkham');
INSERT INTO Artist (Name) VALUES('Veronika Lindroos');
INSERT INTO Artist (Name) VALUES('Barnabas Petrello');
INSERT INTO Artist (Name) VALUES('Liva Tittletross');
INSERT INTO Artist (Name) VALUES('Collie Challens');
INSERT INTO Artist (Name) VALUES('Tessi T');
INSERT INTO Artist (Name) VALUES('Elonore Harcarse');
INSERT INTO Artist (Name) VALUES('Doe Alasdair');
INSERT INTO Artist (Name) VALUES('Tomaso Dumpleton');
INSERT INTO Artist (Name) VALUES('Jacquenetta Bunclark');
INSERT INTO Artist (Name) VALUES('Edmon');
INSERT INTO Artist (Name) VALUES('Gena Ongin');
INSERT INTO Artist (Name) VALUES('Faustina Halpeine');
INSERT INTO Artist (Name) VALUES('Ailina Lars');
INSERT INTO Artist (Name) VALUES('Collin Garvill');
INSERT INTO Artist (Name) VALUES('Jamie Fee Orchestra');
INSERT INTO Artist (Name) VALUES('Casar');
INSERT INTO Artist (Name) VALUES('Bernadina O''Dowd');
INSERT INTO Artist (Name) VALUES('Emilia Gile');
INSERT INTO Artist (Name) VALUES('Dehlia Powlett');
INSERT INTO Artist (Name) VALUES('Robbert');
INSERT INTO Artist (Name) VALUES('Sharia Selesnick');
INSERT INTO Artist (Name) VALUES('Carena Habbon');
INSERT INTO Artist (Name) VALUES('Hammad Bertrand');
INSERT INTO Artist (Name) VALUES('Zed Isakovitch');
INSERT INTO Artist (Name) VALUES('Moshe Ilsley');
INSERT INTO Artist (Name) VALUES('Terencio Breeder');
INSERT INTO Artist (Name) VALUES('Melisande Fansy');
INSERT INTO Artist (Name) VALUES('Dionisio Collier');
INSERT INTO Artist (Name) VALUES('Crysta Kirley');
INSERT INTO Artist (Name) VALUES('Andriette Staley');
INSERT INTO Artist (Name) VALUES('Thaddeus Roc');
INSERT INTO Artist (Name) VALUES('Blondy Starkings');
INSERT INTO Artist (Name) VALUES('Constanta Rosita');
INSERT INTO Artist (Name) VALUES('Codie And Alsopp');
INSERT INTO Artist (Name) VALUES('Tressa Casebourne');
INSERT INTO Artist (Name) VALUES('Lucias Mallya');
INSERT INTO Artist (Name) VALUES('Benedicto');
INSERT INTO Artist (Name) VALUES('Andy Siddaley');
INSERT INTO Artist (Name) VALUES('Darsey Alldritt');
INSERT INTO Artist (Name) VALUES('Olly Connal');
INSERT INTO Artist (Name) VALUES('Daisy Alphonso');
INSERT INTO Artist (Name) VALUES('Jacquetta Haywood');
INSERT INTO Artist (Name) VALUES('Barn Knowlys');
INSERT INTO Artist (Name) VALUES('Helge Pendry');
INSERT INTO Artist (Name) VALUES('Chiquia Joslyn');
INSERT INTO Artist (Name) VALUES('Lyon Ormes');
INSERT INTO Artist (Name) VALUES('Jabez Sego');
INSERT INTO Artist (Name) VALUES('Warren Bambrick');
INSERT INTO Artist (Name) VALUES('Spelman');
INSERT INTO Artist (Name) VALUES('Lil Bartolomucci');
INSERT INTO Artist (Name) VALUES('Clair Lightwing');
INSERT INTO Artist (Name) VALUES('Nikolia Mioni');
INSERT INTO Artist (Name) VALUES('Gnni Coleby');
INSERT INTO Artist (Name) VALUES('Kip G');
INSERT INTO Artist (Name) VALUES('Ariadne Pavey');
INSERT INTO Artist (Name) VALUES('Felipa Meates');
INSERT INTO Artist (Name) VALUES('Hilario Simoneau');
INSERT INTO Artist (Name) VALUES('Estel Siddons');
INSERT INTO Artist (Name) VALUES('Rock Duckerin');
INSERT INTO Artist (Name) VALUES('Talbot Godar');
INSERT INTO Artist (Name) VALUES('Kalinda Cordero');
INSERT INTO Artist (Name) VALUES('Dante McMillan');
INSERT INTO Artist (Name) VALUES('Ianthe Karlsson');
INSERT INTO Artist (Name) VALUES('Dur Jaffra');
INSERT INTO Artist (Name) VALUES('Asia Mechell');
INSERT INTO Artist (Name) VALUES('Nikita Beedham');
INSERT INTO Artist (Name) VALUES('Vivi Zupone');
INSERT INTO Artist (Name) VALUES('Christean Morby');
INSERT INTO Artist (Name) VALUES('Shellie Carberry');
INSERT INTO Artist (Name) VALUES('Camel Mariet');
INSERT INTO Artist (Name) VALUES('Austin Triner');
INSERT INTO Artist (Name) VALUES('Swannie');
INSERT INTO Artist (Name) VALUES('Nicoline Adam');
INSERT INTO Artist (Name) VALUES('Karla Camsey');
INSERT INTO Artist (Name) VALUES('Modestine Domenichelli');
INSERT INTO Artist (Name) VALUES('Melisse Manske');
INSERT INTO Artist (Name) VALUES('Gusti Girl');
INSERT INTO Artist (Name) VALUES('Cassi Garrett');
INSERT INTO Artist (Name) VALUES('Enos Jacqueme');
INSERT INTO Artist (Name) VALUES('Kellie Grinikhinov');
INSERT INTO Artist (Name) VALUES('Viki McMyler');
INSERT INTO Artist (Name) VALUES('Kristyn Klausen');
INSERT INTO Artist (Name) VALUES('Lynelle Edgerley');
INSERT INTO Artist (Name) VALUES('Laural Nestle');
INSERT INTO Artist (Name) VALUES('Garold Nolleth');
INSERT INTO Artist (Name) VALUES('Cosme Ellerker');
INSERT INTO Artist (Name) VALUES('Rickie Raecroft');
INSERT INTO Artist (Name) VALUES('Crookshank');
INSERT INTO Artist (Name) VALUES('Neale Caze');
INSERT INTO Artist (Name) VALUES('OKEY');
INSERT INTO Artist (Name) VALUES('Walliw Hane');
INSERT INTO Artist (Name) VALUES('Emily Quinion');
INSERT INTO Artist (Name) VALUES('Umeko Trotton');
INSERT INTO Artist (Name) VALUES('Nathanael Healey');
INSERT INTO Artist (Name) VALUES('Skelly Balsdone');
INSERT INTO Artist (Name) VALUES('Constancy');
INSERT INTO Artist (Name) VALUES('Marleah Semble');
INSERT INTO Artist (Name) VALUES('Baudoin Dering');
INSERT INTO Artist (Name) VALUES('Irwin Davids');
INSERT INTO Artist (Name) VALUES('Jane Bullivent');
INSERT INTO Artist (Name) VALUES('Dore');
INSERT INTO Artist (Name) VALUES('Skeleton');
INSERT INTO Artist (Name) VALUES('Zak Raikes');
INSERT INTO Artist (Name) VALUES('Sara Mobley');
INSERT INTO Artist (Name) VALUES('Arri Fensome');
INSERT INTO Artist (Name) VALUES('Janina And Kingh');
INSERT INTO Artist (Name) VALUES('Danita Cobbled');
INSERT INTO Artist (Name) VALUES('Larisa');
INSERT INTO Artist (Name) VALUES('Jillian Lefort');
INSERT INTO Artist (Name) VALUES('Charlotta Littlecote');
INSERT INTO Artist (Name) VALUES('Oates Crame');
INSERT INTO Artist (Name) VALUES('Auguste Flement');
INSERT INTO Artist (Name) VALUES('Brianne Geddis');
INSERT INTO Artist (Name) VALUES('Irwin Shipperbottom');
INSERT INTO Artist (Name) VALUES('Abbie Matijasevic');
INSERT INTO Artist (Name) VALUES('Clouston Allstars');
INSERT INTO Artist (Name) VALUES('Merna Langhorne');
INSERT INTO Artist (Name) VALUES('Chrissie Metts');
INSERT INTO Artist (Name) VALUES('Care McClifferty');
INSERT INTO Artist (Name) VALUES('Sheelah Hempshall');
INSERT INTO Artist (Name) VALUES('Vonni Boothebie');
INSERT INTO Artist (Name) VALUES('Wren Fulk');
INSERT INTO Artist (Name) VALUES('Binnie Maton');
INSERT INTO Artist (Name) VALUES('Trudy Facchini');
INSERT INTO Artist (Name) VALUES('Tobit Doneld');
INSERT INTO Artist (Name) VALUES('Paquito Pochin');
INSERT INTO Artist (Name) VALUES('Howell Gang');
INSERT INTO Artist (Name) VALUES('Henri McIndrew');
INSERT INTO Artist (Name) VALUES('Miner D''Adamo');
INSERT INTO Artist (Name) VALUES('Hammad Joysey');
INSERT INTO Artist (Name) VALUES('Culver');
INSERT INTO Artist (Name) VALUES('Gino Bakhrushkin');
INSERT INTO Artist (Name) VALUES('Cariotta Rowthorne');
INSERT INTO Artist (Name) VALUES('Jonas McKniely');
INSERT INTO Artist (Name) VALUES('Richardo Pergens');
INSERT INTO Artist (Name) VALUES('Lulu Filyushkin');
INSERT INTO Artist (Name) VALUES('Guss Latham');
INSERT INTO Artist (Name) VALUES('Kaitlin');
INSERT INTO Artist (Name) VALUES('Gretta Berrane');
INSERT INTO Artist (Name) VALUES('Samara Lemmers');
INSERT INTO Artist (Name) VALUES('Sisely Fullick');
INSERT INTO Artist (Name) VALUES('Janna McPartling');
INSERT INTO Artist (Name) VALUES('Nevins Sirette');
INSERT INTO Artist (Name) VALUES('Page Brugemann');
INSERT INTO Artist (Name) VALUES('Verene Ollerearnshaw');
INSERT INTO Artist (Name) VALUES('Mariam Moggie');
INSERT INTO Artist (Name) VALUES('Vito Batstone');
INSERT INTO Artist (Name) VALUES('Chloris Batecok');
INSERT INTO Artist (Name) VALUES('Imelda Hammelberg');
INSERT INTO Artist (Name) VALUES('Ariana Belchamber');
INSERT INTO Artist (Name) VALUES('Mattie Poynter');
INSERT INTO Artist (Name) VALUES('Almeda Langstrath');
INSERT INTO Artist (Name) VALUES('Blaire Leas');
INSERT INTO Artist (Name) VALUES('Goddart Persehouse');
INSERT INTO Artist (Name) VALUES('Eolanda Portingale');
INSERT INTO Artist (Name) VALUES('Craig Duffit');
INSERT INTO Artist (Name) VALUES('Kelsey Hovenden');
INSERT INTO Artist (Name) VALUES('Mary Mucci');
INSERT INTO Artist (Name) VALUES('Noodles');
INSERT INTO Artist (Name) VALUES('Renate Sukbhans');
INSERT INTO Artist (Name) VALUES('Tommy Bisp');
INSERT INTO Artist (Name) VALUES('Winne Northway');
INSERT INTO Artist (Name) VALUES('Demetri Tocknell');
INSERT INTO Artist (Name) VALUES('Sigrid M');
INSERT INTO Artist (Name) VALUES('Theressa Monk');
INSERT INTO Artist (Name) VALUES('Jonathon Clarkson');
INSERT INTO Artist (Name) VALUES('Dian Sauter');
INSERT INTO Artist (Name) VALUES('FETTY');
INSERT INTO Artist (Name) VALUES('Frans Ashton');
INSERT INTO Artist (Name) VALUES('Devon Ivory');
INSERT INTO Artist (Name) VALUES('Farly Buxcy');
INSERT INTO Artist (Name) VALUES('Rheba De Vile');
INSERT INTO Artist (Name) VALUES('Fowler Traviss');
INSERT INTO Artist (Name) VALUES('Simonne');
INSERT INTO Artist (Name) VALUES('Melisent Waleran');
INSERT INTO Artist (Name) VALUES('Jenny Pendrill');
INSERT INTO Artist (Name) VALUES('Zack Ormston');
INSERT INTO Artist (Name) VALUES('Morena Merchant');
INSERT INTO Artist (Name) VALUES('Carlyle');
INSERT INTO Artist (Name) VALUES('Benoite Okey');
INSERT INTO Artist (Name) VALUES('Lenette Nial');
INSERT INTO Artist (Name) VALUES('Dylan Troupe');
INSERT INTO Artist (Name) VALUES('Clovis Rattray');
INSERT INTO Artist (Name) VALUES('Suzann Pagett');
INSERT INTO Artist (Name) VALUES('Romona Megarrell');
INSERT INTO Artist (Name) VALUES('Dulcea Albasini');
INSERT INTO Artist (Name) VALUES('Skeaty');
INSERT INTO Artist (Name) VALUES('Willa Chainey');
INSERT INTO Artist (Name) VALUES('Dane Aleksankov');
INSERT INTO Artist (Name) VALUES('Skippie Ratledge');
INSERT INTO Artist (Name) VALUES('Rebbecca Coonihan');
INSERT INTO Artist (Name) VALUES('Fabiano Veljes');
INSERT INTO Artist (Name) VALUES('Ginnie Streatley');
INSERT INTO Artist (Name) VALUES('Goldia Folan');
INSERT INTO Artist (Name) VALUES('Nelie Budgett');
INSERT INTO Artist (Name) VALUES('Wini Gerrets');
INSERT INTO Artist (Name) VALUES('Shanna Laybourn');
INSERT INTO Artist (Name) VALUES('Ofella Rylance');
INSERT INTO Artist (Name) VALUES('Silvana Oke');
INSERT INTO Artist (Name) VALUES('Big Desouza');
INSERT INTO Artist (Name) VALUES('Franciska Dealtry');
INSERT INTO Artist (Name) VALUES('Natasha Sitlinton');
INSERT INTO Artist (Name) VALUES('Minna Keyser');
INSERT INTO Artist (Name) VALUES('Daloris Toland');
INSERT INTO Artist (Name) VALUES('Liz Ffrench');
INSERT INTO Artist (Name) VALUES('Cacilia Shortland');
INSERT INTO Artist (Name) VALUES('Goodwyn Gang');
INSERT INTO Artist (Name) VALUES('Emmy S');
INSERT INTO Artist (Name) VALUES('Amelie Collen');
INSERT INTO Artist (Name) VALUES('Fairfax Howley');
INSERT INTO Artist (Name) VALUES('Rosaline Elcoate');
INSERT INTO Artist (Name) VALUES('Yorgo');
INSERT INTO Artist (Name) VALUES('Chantalle Bridal');