INSERT INTO Genre VALUES (1,'Rock');
INSERT INTO Genre VALUES (2,'Jazz');
INSERT INTO Genre VALUES (3,'Metal');
INSERT INTO Genre VALUES (4,'Alternative & Punk');
INSERT INTO Genre VALUES (5,'Rock And Roll');
INSERT INTO Genre VALUES (6,'Blues');
INSERT INTO Genre VALUES (7,'Latin');
INSERT INTO Genre VALUES (8,'Reggae');
INSERT INTO Genre VALUES (9,'Pop');
INSERT INTO Genre VALUES (10,'Soundtrack');
INSERT INTO Genre VALUES (11,'Bossa Nova');
INSERT INTO Genre VALUES (12,'Easy Listening');
INSERT INTO Genre VALUES (13,'Heavy Metal');
INSERT INTO Genre VALUES (14,'R&B/Soul');
INSERT INTO Genre VALUES (15,'Electronica/Dance');
INSERT INTO Genre VALUES (16,'World');
INSERT INTO Genre VALUES (17,'Hip Hop/Rap');
INSERT INTO Genre VALUES (18,'Science Fiction');
INSERT INTO Genre VALUES (19,'TV Shows');
INSERT INTO Genre VALUES (20,'Sci Fi & Fantasy');
INSERT INTO Genre VALUES (21,'Drama');
INSERT INTO Genre VALUES (22,'Comedy');
INSERT INTO Genre VALUES (23,'Alternative');
INSERT INTO Genre VALUES (24,'Classical');
INSERT INTO Genre VALUES (25,'Opera');